---

# CONTROL

- hosts: role_control
  tasks:

    # PACKAGES

    - name: "[A2][INSTALL] Packages"
      apt:
        name: rsync
        state: present

    # VHOSTS

    - name: "[A5][UPDATE] vhosts"
      lineinfile:
        path: /etc/hosts
        line: "{{ item.ip }} {{ item.domain }}"
      with_items: "{{ dokuwiki_sites }}"

# HOSTING

- hosts: role_hosting
  tasks:

    # PACKAGES

    - name: "[A2][INSTALL] Packages"
      apt:
        name:
          - apache2
          - php7.3
          - rsync
        state: present

    # INSTALL

    - name: "[A3][DOWNLOAD] dokuwiki"
      get_url:
        url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: "/usr/src"

    - name: "[CHECK] if dokuwiki is already installed"
      stat:
        path: "/usr/src/dokuwiki"
      register: dokuwiki_directory

    - name: "[A4][UNZIP] dokuwiki archive"
      unarchive:
        remote_src: yes
        src: "/usr/src/dokuwiki-stable.tgz"
        dest: "/usr/src"
      when: not dokuwiki_directory.stat.exists

    - name: "[RENAME] dokuwiki with version to a no-version one"
      command: "mv /usr/src/dokuwiki-{{  dokuwiki_version }} /usr/src/dokuwiki"
      when: not dokuwiki_directory.stat.exists

    - name: "[REMOVE] archive"
      file:
        path: "/usr/src/dokuwiki-stable.tgz"
        state: absent

      # MANAGE FOLDERS FOR APACHE

    - name: "[B1][CREATE] directory for each website"
      file:
        state: directory
        path: "/var/www/{{ item.config }}"
        owner: www-data
        group: www-data
      with_items: "{{ dokuwiki_sites }}"

    - name: "[B2][SYNC] dokuwiki with destination directory"
      synchronize:
        # archive: true # keep origin permission
        src: /usr/src/dokuwiki/
        dest: "/var/www/{{ item.config }}/" # if you put a "/" at the end you're sending only the content
      with_items: "{{ dokuwiki_sites }}"
      delegate_to: "{{ inventory_hostname }}" # source is current machine

    - name: "[B3][UPDATE] folder's permissions"
      file:
        path: "/var/www/{{ item.config }}/"
        state: directory
        recurse: true
        group: www-data
        owner: www-data
      with_items: "{{ dokuwiki_sites }}"

    # VHOSTS

    - name: "[MANAGE] Vhosts config"
      template:
        src: templates/etc.apache2.site-available.site.apache2.conf
        dest: "/etc/apache2/sites-available/{{ item.config }}.conf"
      with_items: "{{ dokuwiki_sites }}"

    - name: "[RUN] enable apache config"
      command: "a2ensite {{ item.config }}"
      with_items: "{{ dokuwiki_sites }}"

    - name: "[RUN] reload apache service"
      service:
        name: apache2
        state: reloaded