---
## Play
- hosts: role_hosting
  tasks:

    # PACKAGES

    - name: "[INSTALL] Packages"
      apt:
        name:
          - apache2
          - php7.3
        state: present

    # INSTALL

    - name: "[DOWNLOAD] dokuwiki"
      get_url:
        url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: "/usr/src"

    - name: "[UNZIP] dokuwiki archive"
      unarchive:
        remote_src: yes
        src: "/usr/src/dokuwiki-stable.tgz"
        dest: "/usr/src"

    - name: "[REMOVE] archive"
      file:
        path: "/usr/src/dokuwiki-stable.tgz"
        state: absent

    - name: "[RENAME] dokuwiki file to an unversioned one"
      command: mv /usr/src/dokuwiki-2020-07-29 /usr/src/dokuwiki

      # MANAGE FOLDERS FOR APACHE

    - name: "[CREATE] directory recettes_wiki"
      command: cp -r /usr/src/dokuwiki /var/www/recettes_wiki

    - name: "[UPDATE] folder's owner"
        file:
          path: /var/www/recettes_wiki
          state: directory
          recurse: yes
          owner: www-data
          group: www-data

    - name: "[CREATE] directory politique_wiki"
        command: cp -r /usr/src/dokuwiki /var/www/politique_wiki

    - name: "[UPDATE] folder's owner"
        file:
          path: /var/www/politique_wiki
          state: directory
          recurse: yes
          owner: www-data
          group: www-data

    # VHOSTS - RECETTES

    - name: "[UPDATE] vhost - recettes"
      lineinfile:
        dest: /etc/hosts
        line: "127.0.0.1    recettes.wiki"

    - name: "[COPY] VHost from host to VM - recettes"
        copy:
          src: files/recettes-wiki.conf
          dest: /etc/apache2/sites-available/recettes-wiki.conf

    - name: "[RUN] enable config for vhost - recettes"
        command: a2ensite recettes-wiki

    # VHOSTS - POLITIQUE

    - name: "[UPDATE] vhost - politique"
        lineinfile:
          dest: /etc/hosts
          line: "127.0.0.1    politique.wiki"

    - name: "[COPY] VHost from host to VM - politique"
        copy:
          src: files/recettes-wiki.conf
          dest: /etc/apache2/sites-available/politique-wiki.conf

    - name: "[RUN] enable config for vhost - politique"
        command: a2ensite recettes-wiki